### ISSUE TITLE
what is the reasoning behind the alphabetic layout?

### ISSUE THREAD

**Issue by nobodyatandnothing** [jackrosenthal/threelayout#38]
hi, the modifying keyscheme is awesome, thank you.
why did you put the letters where you put them ?

**Comment by jackrosenthal** [comment]
Some of it is in the readme:

* **increase hand alternation**: inspired by dvorak, the majority of consonants are on the right side
* **reduce bottom-to-top row jumps**: initially, I disliked the idea of the bottom row entirely, to the point that on the initial versions of [my old layout](https://github.com/jackrosenthal/wuly-antimak), I had 11 letters on the top row and 10 on home row, leaving only 5 on the bottom row (compare to QWERTY's 7). 11 on the top turned out to be a bit unbalanced, and I learned from this mistake, but figured out something new in the process: using the bottom row isn't so difficult as long as you don't have to jump from bottom to top row on the same finger (or visa versa). Going to some of the least frequent bigraphs in English, I decided on the current set `3L` has for reducing bottom & top row jumps: `MF`, `JU`, `JZ`, `GX`, `GK`, `LX`, `LK`, and `VW`.
* **decrease lateral motion**: This one I learned from a few keyboards before that I made: reaching to the center keys is a little tough and straining, so reduce it where I can. Put an infrequent key like `;` in the hardest to reach spot on the keyboard.

But ultimately, the best answer is that the letter placement here was determined thru nothing but experience: many trials, and many failures.

- The first alt keyboard layout I used was Colemak, which I abandoned after only a few months as I never got what I came for: making it easier to write code. The symbols were all still a hunt and peck to the digits on the top row.
- After this experience, I tried learning Programmer's Dvorak for a few days only to decide that it had similar issues.
- A friend at university had made a Neo derivative called (Antibracket)[https://github.com/pianohacker/antibracket]. I tried this one for a few days too, but was ultimately turned away by the fact that I had a ton of work to finish and no keyboard to type on quickly anymore.
- In a rush to get a lab report done, I made my [own keyboard layout based on Antibracket](https://github.com/jackrosenthal/wuly-antimak), which essentially combined the parts of Colemak I needed to get the lab report done quickly, with some of the other parts of Antibracket. To be expected, when you force two layouts to combine, you'll end up with something extremely quirky. I could type fast on the keyboard, but ultimately I found over long term use that it was uncomfortable, which I didn't like.
- Later that year, I made a [heavily revised version of my keyboard layout](https://user-images.githubusercontent.com/840735/140992716-38f711ba-fada-46e7-8b67-6a9da15cb203.jpg), trying to fix some of the quirks. This is the first keyboard layout starting to really show the resemblance to 3l today. I never went far beyond the initial stages of learning it, partly as I figured out initial quirks of the layout pretty quickly.
- Around this time I built an ErgoDox keyboard and wanted to think about how I could make a layout specifically designed for the ErgoDox. I started looking into [ADNW keyboard](http://www.adnw.de), which was based on Neo and built for German. There's many aspects of this layout I liked, but I needed to clear out some of the German stuff and pave way for English typing. I made a variant of it, but within only a few weeks of typing on it, discovered issues that resulted from adopting a German layout for English usage: there's just completely different letter frequencies and bigraphs used in German, and the keyboard was extremely quirky as a result. I abandoned it.
- The next keyboard layout I would make would be [3L](https://user-images.githubusercontent.com/840735/140992713-e905586c-88df-4fcc-b022-0f79f4fc4e2f.jpg). Some of the letter positioning was decided by analyzing both English text and code (mostly Python and C) corpuses on my hard drive, creating charts of common bigraphs and trigraphs, but the majority of it was just what "felt right" and learning from the mistakes of the previous three layouts I had made.

Ultimately designing a keyboard layout is a system of tradeoffs. You fix one thing and another thing gets worse. There is no perfect keyboard layout. It's a matter of choosing which tradeoffs are the right ones for you.

Perhaps one day I'll clean up this a bit and turn it into something that could go on a website for the layout.

**Comment by nobodyatandnothing** [comment]
> * **increase hand alternation**: inspired by dvorak, the majority of consonants are on the right side

it would seem that the a and the r would be better if they were switched. is this why they aren't?

**Comment by jackrosenthal** [comment]
> it would seem that the a and the r would be better if they were switched. is this why they aren't?

I don't remember the exact reasoning behind the placement of A and R. However A is probably best grouped with the vowels given most english usages.
